name: Build Hexo

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 环境设置
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 依赖安装
        run: yarn

      - name: 构建博客
        run: yarn build

      - name: 存档
        uses: actions/upload-artifact@v4
        with:
          name: blog
          path: public
          retention-days: 7
          overwrite: true

      - name: 部署
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.BLOG_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: public/**
          target: /home/blog/
          overwrite: true
          debug: true
          strip_components: true