name: Build Hexo

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Build Hexo
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blog
          path: public
          retention-days: 7
          overwrite: true
